// Generated by Xata Codegen 0.21.0. Please do not edit.
import { buildClient } from "@xata.io/client";
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "quiz",
    columns: [
      { name: "questions", type: "string" },
      { name: "answer", type: "int" },
      { name: "options", type: "multiple" },
      { name: "selected", type: "int" },
    ],
  },
  {
    name: "users",
    columns: [
      { name: "username", type: "string" },
      { name: "email", type: "email" },
      { name: "password", type: "string" },
    ],
  },
];
/** @type { import('../../client/src').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
  enableBrowser: true,
  apiKey: "xau_ZYSXounA3R8SV137uHIxawD1hctsA2h93",
  databaseURL:
    "https://Marcel-Alexis-s-workspace-t2ur68.us-east-1.xata.sh/db/Questions",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
let instance = undefined;
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
